application:
  subdomain: bracket
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      domain_prefix: api
      backend: http://bracket-backend:8400/

    - location: /
      backend: http://bracket-frontend:3000/

services:
  bracket-backend:
    # upstream: ghcr.io/evroon/bracket-backend:v2.2.5
    image: ghcr.io/evroon/bracket-backend:v2.2.5
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - AUTO_RUN_MIGRATIONS=true
      - ADMIN_EMAIL={{.U.admin_email}}
      - ADMIN_PASSWORD={{.U.admin_password}}
      - CORS_ORIGINS=https://{{.S.AppDomain}}
      - PG_DSN=postgresql://bracket_dev:{{ stable_secret "db_password" }}@postgres:5432/bracket_dev
    depends_on:
      - postgres
    healthcheck:
      disable: true
      start_period: 90s

  bracket-frontend:
    # upstream: ghcr.io/evroon/bracket-frontend:v2.2.5
    image: ghcr.io/evroon/bracket-frontend:v2.2.5
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://api-{{.S.AppDomain}}
      - NEXT_PUBLIC_HCAPTCHA_SITE_KEY=10000000-ffff-ffff-ffff-000000000001
    healthcheck:
      disable: true
      start_period: 90s

  postgres:
    # upstream: library/postgres:16.15-alpine
    image: library/postgres:16.15-alpine
    environment:
      - POSTGRES_DB=bracket_dev
      - POSTGRES_PASSWORD={{ stable_secret "db_password" }}
      - POSTGRES_USER=bracket_dev
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U bracket_dev
      start_period: 90s
